//Open packet.h find
	GUILD_SUBHEADER_GC_GUILD_WAR_END_LIST,
	GUILD_SUBHEADER_GC_WAR_SCORE,
	GUILD_SUBHEADER_GC_MONEY_CHANGE,
//add
#ifdef ENABLE_GUILDBANK_LOG
	GUILD_SUBHEADER_GC_BANK_INFO,
	GUILD_SUBHEADER_GC_BANK_DELETE,
#endif

//find
	GUILD_SUBHEADER_CG_CHARGE_GSP,
	GUILD_SUBHEADER_CG_DEPOSIT_MONEY,
	GUILD_SUBHEADER_CG_WITHDRAW_MONEY,
//add
#ifdef ENABLE_GUILDBANK_LOG
	GUILD_SUBHEADER_CG_REFRESH,
#endif
