//Open tables.h find 
	HEADER_GD_REQUEST_CHARGE_CASH	= 137,

	HEADER_GD_DELETE_AWARDID	= 138,	// delete gift notify icon
	
	HEADER_GD_UPDATE_CHANNELSTATUS	= 139,
	HEADER_GD_REQUEST_CHANNELSTATUS	= 140,
//add
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
	HEADER_GD_GUILDSTORAGE_LOAD					= 150,
	HEADER_GD_GUILDSTORAGE_CHANGE_SIZE			= 151,
#endif
//find
	HEADER_DG_SAFEBOX_LOAD					= 45,
	HEADER_DG_SAFEBOX_CHANGE_SIZE			= 46,
	HEADER_DG_SAFEBOX_WRONG_PASSWORD		= 47,
	HEADER_DG_SAFEBOX_CHANGE_PASSWORD_ANSWER = 48,

	HEADER_DG_EMPIRE_SELECT		= 49,

	HEADER_DG_AFFECT_LOAD		= 50,
	HEADER_DG_MALL_LOAD			= 51,
//add
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
	HEADER_DG_GUILDSTORAGE_LOAD					= 52,
	HEADER_DG_GUILDSTORAGE_CHANGE_SIZE			= 53,
#endif

//add with the others typedef
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
typedef struct SGuildstorageChangeSizePacket
{
	DWORD dwID;
	BYTE bSize;
} TGuildstorageChangeSizePacket;
#endif
