//Open packet.h find:
	GUILD_SUBHEADER_GC_GUILD_NAME,
	GUILD_SUBHEADER_GC_GUILD_WAR_LIST,
	GUILD_SUBHEADER_GC_GUILD_WAR_END_LIST,
	GUILD_SUBHEADER_GC_WAR_SCORE,
	GUILD_SUBHEADER_GC_MONEY_CHANGE,
//add
#if defined(ENABLE_GUILD_LAND_INFO)
	GUILD_SUBHEADER_GC_LAND_INFO,
#endif
