//Open db.h find
	// PCBANG_IP_LIST
	QID_PCBANG_IP_LIST_CHECK,
	QID_PCBANG_IP_LIST_SELECT,
	// END_OF_PCBANG_IP_LIST

	// PROTECT_CHILD_FOR_NEWCIBN
	QID_PROTECT_CHILD,
	// END_PROTECT_CHILD_FOR_NEWCIBN
//add
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
	QID_GUILDSTORAGE_SIZE,
#endif
