//Open packet.h find
	HEADER_CG_SAFEBOX_ITEM_MOVE			= 77,
	HEADER_CG_PARTY_PARAMETER			= 78,

	HEADER_CG_GUILD				= 80,
	HEADER_CG_ANSWER_MAKE_GUILD			= 81,

	HEADER_CG_FISHING				= 82,

	HEADER_CG_ITEM_GIVE				= 83,
//add
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
	HEADER_CG_GUILDSTORAGE_CHECKIN				= 84,
	HEADER_CG_GUILDSTORAGE_CHECKOUT				= 85,
#endif
//find 
	// SUPPORT_BGM
	HEADER_GC_MAIN_CHARACTER3_BGM		= 137,
	HEADER_GC_MAIN_CHARACTER4_BGM_VOL	= 138,
	// END_OF_SUPPORT_BGM
//add
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
	HEADER_GC_GUILDSTORAGE_OPEN					= 141,
	HEADER_GC_GUILDSTORAGE_SET					= 142,
	HEADER_GC_GUILDSTORAGE_DEL					= 143,
#endif
//find
enum
{
	GUILD_SUBHEADER_GG_CHAT,
	GUILD_SUBHEADER_GG_SET_MEMBER_COUNT_BONUS,
//add
#if defined(ENABLE_GUILDRENEWAL_SYSTEM) && defined(ENABLE_GUILDSTORAGE_SYSTEM)
	GUILD_SUBHEADER_GG_REFRESH,
	GUILD_SUBHEADER_GG_REFRESH1,
#endif
};

//add with others typedef
#ifdef ENABLE_GUILDSTORAGE_SYSTEM
typedef struct packet_guildstorage_open
{
	BYTE bHeader;
	BYTE bSize;
} TPacketGCGuilds
