//open packet.h find 
	GUILD_SUBHEADER_GC_GUILD_WAR_END_LIST,
	GUILD_SUBHEADER_GC_WAR_POINT,
	GUILD_SUBHEADER_GC_MONEY_CHANGE,
//add
#ifdef ENABLE_GUILD_WAR_SCORE
	GUILD_SUBHEADER_GC_WAR_INFO,
#endif
